apply plugin: 'com.android.application'

android {
    compileSdk = 37
    namespace = "com.gemalto.jp2.test"

    defaultConfig {
        applicationId "com.gemalto.openjpeg.test"
        minSdk 16
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            //TODO update the path to your keystore and the related variables
            if (project.hasProperty('defaultKeyStoreFile')) storeFile file(defaultKeyStoreFile)
            if (project.hasProperty('defaultKeyStorePassword')) storePassword defaultKeyStorePassword
            if (project.hasProperty('defaultKeyAlias')) keyAlias defaultKeyAlias
            if (project.hasProperty('defaultKeyPassword')) keyPassword defaultKeyPassword
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    configurations.configureEach {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                details.useVersion '1.8.22'
            }
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':jp2-android')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core:1.12.0'
}
